### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by samirotiv** [fallenhitokiri/autocomplete-plus-jedi#3] opened 2015-03-01 13:39 UTC
I just opened a Python file, and typed "csv." at a point, and this showed up.

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-plus-jedi](https://github.com/fallenhitokiri/autocomplete-plus-jedi) package, v0.0.6
### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///C:/Users/Samir/AppData/Local/atom/app-0.182.0/resources/app/static/index.html?loadSettings=%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CSamir%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.182.0%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CSamir%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.182.0%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.182.0%22%2C%22shellLoadTime%22%3A1062%2C%22initialPaths%22%3A%5B%5D%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at C:\Users\Samir\.atom\packages\autocomplete-plus-jedi\lib\jedi-provider.coffee:36:29
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -33:22.3 settings-view:open (atom-text-editor.editor)
  2x -33:10.4 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-unity-ui)
     -32:27.2 core:backspace (atom-text-editor.editor.mini)
     -32:26.6 core:confirm (atom-text-editor.editor.mini)
     -30:30.3 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-unity-ui)
     -30:30.1 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-unity-ui)
  2x -30:23.1 core:close (div.settings-view.pane-item)
  2x -30:08.9 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "auto-detect-indentation",
      "autocomplete",
      "symbols-view",
      "symbols-tree-view",
      "linter",
      "sync-settings"
    ],
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.6.0
autocomplete-plus, v2.2.0
autocomplete-plus-jedi, v0.0.6
file-icons, v1.5.0
indent-guide-improved, v1.1.1
indentation-indicator, v0.4.1
line-ending-converter, v1.0.0
unity-ui, v2.0.3

# Dev
No dev packages
```

**Comment by fallenhitokiri** [comment] 2015-03-01 13:54
I just pushed a new version to react to errors thrown by the completion library. If it still happens would it be possible that you upload the Python file you are talking about somewhere so I can test with the file?

**Comment by samirotiv** [comment] 2015-03-01 15:58
The same file shows the same error when I try typing "csv." in the file.

Moreover, something weird is happening. If I just blindly delete the second half of the file, the error doesn't show up, but nothing happens. As in, it doesn't show me any completions.

I thought that this could be due to a conflict from atom-ctags, so I disabled atom-ctags and tried again, but it still doesn't work.

Can I send this file to you privately for your testing, since I unfortunately can't post it here? How about email?

EDIT: I've sent the file over to the email address listed in your profile. Cheers!.

**Comment by fallenhitokiri** [comment] 2015-03-02 10:43
got your mail, thanks. I'll keep the conversation - not referencing the file you sent - in this issue to keep anyone with this or a similar issue updated.

**Comment by samirotiv** [comment] 2015-03-03 11:34
Glad to hear that you traced it.! I will be a willing guinea pig for the next release.

**Comment by rvm521443** [comment] 2015-03-05 03:23
The problem is with Windows command line, single quotes can't be used to escape input, i.e. `python jedi-complete.py 'from djan' 0 4 \` won't fly. You have to use double quotes for that.

Also, I haven't found a proper way to escape newlines.

Basically, I ended up [forking](https://github.com/rvm521443/autocomplete-plus-jedi) your plugin and using [python-shell](https://www.npmjs.com/package/python-shell) package to deal with this stuff in a cross platform fashion and now everything just works.

**Comment by fallenhitokiri** [comment] 2015-03-05 06:45
The new release this week should solve this. It uses a long running Pyhton process instead of executing the completion script in every keystroke. Escaping and forking introduce several other problems that go will be fixed.

**Comment by fallenhitokiri** [comment] 2015-03-10 12:40
0.0.8 was just published introducing the completion daemon - please let me know if this solves this problem

**Comment by samirotiv** [comment] 2015-03-11 11:42
Hi Timo,
I regret to inform you, but it doesn't. The identical error shows up.

I guess there's something else that's causing the trouble!

EDIT: Ran it again, the error isn't showing up now, but it isn't showing me any suggestions.

Samir.

**Comment by fallenhitokiri** [comment] 2015-03-11 12:31
I'll fire up a Windows VM the next few days and take a closer look. Still the same file?

**Comment by samirotiv** [comment] 2015-03-13 21:30
Could the problem be about Python versions, by any chance?? I'm running Python 3.4.3.

Also, on another different machine, I have multiple Python installations. Is there a way I can specify which installation to use?

Edit: Figured out the second answer - I can edit your code and just hardcode the path of the python executable.

**Comment by samirotiv** [comment] 2015-03-15 18:58
Again, awfully sorry to bother you, Timo, but I just mean to ask if I'm missing something. :)

I installed the plugin on Atom 0.187 on OS X Yosemite. I confirm that I'm running the bundled version of Python, and I've installed Jedi. I tried doing "import jedi" in a Python script to test, and it worked.

Unfortunately when I open a Python file in Atom and try doing Autocompletions, nothing seems to happen. Not sure if I'm missing something..!!

**Comment by fallenhitokiri** [comment] 2015-03-15 19:16
I found a problem if you are on Python 3 - I have some other bugs to fix, I’ll push an update somewhere tomorrow or Tuesday.

**Comment by fallenhitokiri** [comment] 2015-03-24 21:02
@samirotiv Python 3 support was just pushed with 0.0.9 thanks to @tinloaf

**Comment by samirotiv** [comment] 2015-03-25 05:09
Thanks a lot, Timo & @tinloaf, it works beautifully now. :)

Just a quick question - can I get it to show function parameters?

**Comment by fallenhitokiri** [comment] 2015-03-25 08:33
when you start typing function parameters should show up as completion.

I working on a popup to either show the whole signature + docstring or as an alternative just inserting all parameters on completion. Not sure what it'll be yet or if I start with the later as temporary solution.

**Closed as completed by fallenhitokiri** 2015-03-25 08:33 UTC
